version: '3'
services:

############## Greenplum 6 master node ################### 
  greenplum-6:
    build:
      context: . 
      dockerfile: DockerFile_6

    ports:
      - 5432:5432  

    hostname: 'greenplum-6'
    container_name: 'greenplum-6'

    healthcheck:
      test: ["CMD-SHELL", "/usr/local/gpdb/bin/psql -h greenplum -U gpadmin -d postgres -c \"SELECT 2+2;\" | grep 4"]
      start_period: 5s
      interval: 60s
      timeout: 60s
      retries: 5      

    ulimits:
      nproc: 131072
      nofile:
        soft: 524288
        hard: 524288

    environment: 
     - LANG=en_US.UTF-8 
     - LANGUAGE=en_US:en 
     - LC_ALL=en_US.UTF-8     
     
    volumes:
      - greenplum-6-data:/data
      - ./s3.conf:/home/gpadmin/s3.conf
      
volumes:
  greenplum-6-data: